---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"
  - "12"

sudo: false
dist: trusty

before_install:
  - npm i -g pnpm
  - pnpm --version # Optional: verify pnpm installation

script:
  - pnpm build
  - pnpm test-single-run
